version: '3'
services: 
    mongodb:
        image: mongo:4
        ports:
            - 27017:27017
    app:
        build: .
        image: app
        command: npm run dev:watch
        ports:
            - 4000:4000
        environment: 
            MONGO_URL: mongodb
            PORT: 4000
        volumes: 
            - ./:/src/
            - nodemodules:/src/node_modules
        links: 
            - mongodb
        depends_on: 
            - mongodb

volumes: 
    nodemodules: {}